### ISSUE TITLE
W.S Toh - Do you do paid consultation work?

### ISSUE THREAD

**Issue by christoferd** [code-boxx/I-Was-Here#3]
Hi WS Toh, 

Do you do paid consultation work?

I ran into your "I was here PHP attendance system" when researching password-less auth for a client. NFC was the my first thought, then I started researching USB Fingerprint readers, but I can't seem to find anything that helps it work with the web.

If I could just pay you to answer some questions and point me in the right direction to solve the issue it would be great.

Cheers, Chris DeDavid

**Comment by code-boxx** [comment]
Don't think you will want to pay a senior web dev to take unpaid leave, pay to take my time off content creation, and top up to make my time worth it...

P.S. Search for WebAuthn, I have a simplified tutorial/example here - https://code-boxx.com/simple-php-webauthn/
